### PR TITLE
Removed useless code

### PR DESCRIPTION
**Pull request by TheSchaft**

### CODE REVIEW

**Comment by connormlewis** [comment]
Are you only wanting to merge the one last commit?

**Comment by TheSchaft** [comment]
Yeah, If doing the whole pull request is too much then you can just merge the changes into your personal branch

**Comment by connormlewis** [comment]
I just think this has had the filter branch merged into it, which I don't know if they want to merge yet

**Comment by connormlewis** [comment]
I'm going to close this and open another one with just that one commit

**Comment by TheSchaft** [comment]
I think I have merged the changes from the filter branch. It can wait, it's not a significant change, It's just clean up

**Pull request closed without merging**
